# 서울시 군구별 입력값을 받아 시각화하기
### - 지역명 입력 -> 2013-2021 포인트&라인 차트로 표현

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("../Data/seoul_3.csv")
df

     시군구    년도   전출인구  출생아수  산부인과의원수  초등학교수  cluster_id  pred_cluster
0    종로구  2013  30007   873        9     14        1.00      0.969258
1    종로구  2014  27484   905        9     14        1.00      1.004041
2    종로구  2015  27470   906        9     14        1.00      1.004230
3    종로구  2016  26386   846        9     13        1.00      1.017994
4    종로구  2017  25814   689        9     13        1.00      1.026642
..   ...   ...    ...   ...      ...    ...         ...           ...
220  강동구  2017  90819  2968       18     27        0.00      0.141560
221  강동구  2018  68933  2659       17     27        0.33      0.445547
222  강동구  2019  67292  2437       17     27        0.33      0.469296
223  강동구  2020  78271  2535       17     28        0.33      0.318357
224  강동구  2021  74444  2810       19     29        0.33      0.372520

[225 rows x 8 columns]

In [18]:
gungu = '종로구'
# df[df['시군구'] == gungu][['년도','pred_cluster']].to_dict()
# df[df['시군구'] == gungu][['년도','pred_cluster']].to_dict('list')
df[df['시군구'] == gungu][['년도']]

     년도
0  2013
1  2014
2  2015
3  2016
4  2017
5  2018
6  2019
7  2020
8  2021

In [7]:
gungu = '종로구'
df[df['시군구'] == gungu]['pred_cluster'].tolist()

[0.969257663705784,
 1.004041010371882,
 1.0042302076494145,
 1.0179941419548224,
 1.0266416988205942,
 1.040917213914866,
 1.0521278343566312,
 1.035137023378372,
 1.0475078078362607]

In [ ]:
from flask import Flask, jsonify, render_template, request # 플라스크에 대한 얘기임
import joblib

app = Flask(__name__)

@app.route("/gungu")
def seoul_gungu():
    gungu = request.args.get("gungu")
    df = pd.read_csv("./PythonSpace/seoul_3.csv")
    df
    
    # gungu = '종로구'
    res = df[df['시군구'] == gungu]['pred_cluster'].tolist()
    print(gungu)

    return jsonify({'result' : res})


# 내가실행하는게 아니라 플러터에서 실행하는것   # 파이썬에서는 런메소드가 제일 뒤에 있다.
if __name__ == "__main__": # 자바의 메인 메소드
    app.run(host="127.0.0.1", port=5000, debug=True)


# 크롬으로 잘돌아가는지 확인하고, 소스보기로 이상한 소스 없는지도 확인하기 <