# (kosis) 시도별·산업별·기업규모별 기업수 
https://kosis.kr/statHtml/statHtml.do?orgId=142&tblId=DT_BR301&conn_path=I2

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings 

warnings.filterwarnings('ignore')

In [5]:
companies = pd.read_csv("../Companies/Data/시도별·산업별·기업규모별_기업수_20230207122624.csv", encoding="euc-kr")

In [7]:
companies

,지역별,산업별(10차)대분류,2019,2019.1,2019.2,2019.3,2019.4,2019.5,2020,2020.1,2020.2,2020.3,2020.4,2020.5
0,지역별,산업별(10차)대분류,전체,소상공인,소기업,중기업,중소기업,대기업,전체,소상공인,소기업,중기업,중소기업,대기업
1,전국,전산업,6898958,6445316,344611,100276,6890203,8755,7295393,6842959,338865,104199,7286023,9370
2,전국,"A. 농업, 임업 및 어업(01~03)",88516,83950,4303,193,88446,70,95548,90686,4557,226,95469,79
3,전국,B. 광업(05~08),2656,2357,202,88,2647,9,2597,2292,206,87,2585,12
4,전국,C. 제조업(10~34),579197,504101,59526,12947,576574,2623,587778,513192,59192,12767,585151,2627
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
338,제주,"N. 사업시설관리, 사업지원 및 임대 서비스업(74~76)",3067,2734,281,47,3062,5,3381,3056,268,49,3373,8
339,제주,P. 교육 서비스업(85),X,3047,116,10,3173,X,X,3350,125,11,3486,X
340,제주,Q. 보건업 및 사회복지 서비스업(86~87),1031,534,350,147,1031,-,1054,566,329,159,1054,-
341,제주,"R. 예술, 스포츠 및 여가관련 서비스업(90~91)",2431,2279,113,28,2420,11,2637,2491,113,24,2628,9
342,제주,"S. 협회및단체,수리및기타개인서비스업(94~96)",X,5221,154,75,5450,X,X,5452,143,75,5670,X