# 서울시 군구별 입력값을 받아 시각화하기
### - 지역명 입력 -> 2013-2021 포인트&라인 차트로 표현

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../Data/seoul_3.csv")
df

     시군구    년도   전출인구  출생아수  산부인과의원수  초등학교수  cluster_id  pred_cluster
0    종로구  2013  30007   873        9     14        1.00      0.969258
1    종로구  2014  27484   905        9     14        1.00      1.004041
2    종로구  2015  27470   906        9     14        1.00      1.004230
3    종로구  2016  26386   846        9     13        1.00      1.017994
4    종로구  2017  25814   689        9     13        1.00      1.026642
..   ...   ...    ...   ...      ...    ...         ...           ...
220  강동구  2017  90819  2968       18     27        0.00      0.141560
221  강동구  2018  68933  2659       17     27        0.33      0.445547
222  강동구  2019  67292  2437       17     27        0.33      0.469296
223  강동구  2020  78271  2535       17     28        0.33      0.318357
224  강동구  2021  74444  2810       19     29        0.33      0.372520

[225 rows x 8 columns]

In [3]:
gungu = '종로구'
# df[df['시군구'] == gungu][['년도','pred_cluster']].to_dict()
# df[df['시군구'] == gungu][['년도','pred_cluster']].to_dict('list')
df[df['시군구'] == gungu][['년도']]

     년도
0  2013
1  2014
2  2015
3  2016
4  2017
5  2018
6  2019
7  2020
8  2021

In [4]:
df['pred_cluster'] = round(df['pred_cluster'],2)

In [5]:
gungu = '종로구'
df[df['시군구'] == gungu]['pred_cluster'].tolist()

[0.97, 1.0, 1.0, 1.02, 1.03, 1.04, 1.05, 1.04, 1.05]

In [ ]:
# from flask import Flask, jsonify, render_template, request # 플라스크에 대한 얘기임
# import joblib

# app = Flask(__name__)

# @app.route("/gungu")
# def seoul_gungu():
#     gungu = request.args.get("gungu")
#     df = pd.read_csv("./PythonSpace/seoul_3.csv")
#     df
    
#     # gungu = '종로구'
#     res = df[df['시군구'] == gungu]['pred_cluster'].tolist()
#     print(gungu)

#     return jsonify({'result' : res})


# # 내가실행하는게 아니라 플러터에서 실행하는것   # 파이썬에서는 런메소드가 제일 뒤에 있다.
# if __name__ == "__main__": # 자바의 메인 메소드
#     app.run(host="127.0.0.1", port=5000, debug=True)


# # 크롬으로 잘돌아가는지 확인하고, 소스보기로 이상한 소스 없는지도 확인하기 <

----

In [7]:
pd.DataFrame(df[['년도','시군구','pred_cluster']])

       년도  시군구  pred_cluster
0    2013  종로구          0.97
1    2014  종로구          1.00
2    2015  종로구          1.00
3    2016  종로구          1.02
4    2017  종로구          1.03
..    ...  ...           ...
220  2017  강동구          0.14
221  2018  강동구          0.45
222  2019  강동구          0.47
223  2020  강동구          0.32
224  2021  강동구          0.37

[225 rows x 3 columns]

In [8]:
gungu_list = df['시군구'].unique()
gungu_list

array(['종로구', '중구', '용산구', '성동구', '광진구', '동대문구', '중랑구', '성북구', '강북구',
       '도봉구', '노원구', '은평구', '서대문구', '마포구', '양천구', '강서구', '구로구', '금천구',
       '영등포구', '동작구', '관악구', '서초구', '강남구', '송파구', '강동구'], dtype=object)

In [9]:
gungu_dict = {}
gungu_dict['년도'] = df['년도'].unique().tolist()
gungu_dict['군구'] = df['시군구'].unique().tolist()
for gungu in gungu_list:
    gungu_dict[gungu] = df['pred_cluster'][df['시군구'] == gungu].tolist()
gungu_dict

{'년도': [2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021],
 '군구': ['종로구',
  '중구',
  '용산구',
  '성동구',
  '광진구',
  '동대문구',
  '중랑구',
  '성북구',
  '강북구',
  '도봉구',
  '노원구',
  '은평구',
  '서대문구',
  '마포구',
  '양천구',
  '강서구',
  '구로구',
  '금천구',
  '영등포구',
  '동작구',
  '관악구',
  '서초구',
  '강남구',
  '송파구',
  '강동구'],
 '종로구': [0.97, 1.0, 1.0, 1.02, 1.03, 1.04, 1.05, 1.04, 1.05],
 '중구': [1.07, 1.06, 1.06, 1.08, 1.1, 1.09, 1.11, 1.08, 1.09],
 '용산구': [0.83, 0.82, 0.81, 0.85, 0.88, 0.86, 0.89, 0.84, 0.84],
 '성동구': [0.73, 0.68, 0.71, 0.74, 0.75, 0.71, 0.72, 0.66, 0.75],
 '광진구': [0.55, 0.5, 0.5, 0.55, 0.61, 0.58, 0.6, 0.56, 0.61],
 '동대문구': [0.61, 0.56, 0.55, 0.62, 0.66, 0.6, 0.65, 0.59, 0.69],
 '중랑구': [0.48, 0.44, 0.4, 0.49, 0.56, 0.57, 0.62, 0.53, 0.59],
 '성북구': [0.41, 0.34, 0.34, 0.43, 0.46, 0.5, 0.56, 0.46, 0.54],
 '강북구': [0.65, 0.65, 0.66, 0.7, 0.76, 0.75, 0.79, 0.74, 0.79],
 '도봉구': [0.66, 0.68, 0.66, 0.72, 0.77, 0.78, 0.82, 0.73, 0.8],
 '노원구': [0.26, 0.25, 0.26, 0.29, 0.33, 0.41, 0.48, 0.35, 0.48],
 '은평구': [0.33, 0.28, 0.22, 0.25, 0.38, 0.41, 0.4, 0.35, 0.48],
 '서대문구': [0.7, 0.69, 0.62, 0.63, 0.69, 0.72, 0.74, 0.65, 0.74],
 '마포구': [0.49, 0.46, 0.39, 0.39, 0.51, 0.55, 0.57, 0.45, 0.54],
 '양천구': [0.45, 0.42, 0.42, 0.37, 0.53, 0.54, 0.62, 0.47, 0.57],
 '강서구': [0.21, 0.06, 0.09, 0.11, 0.2, 0.15, 0.23, 0.03, 0.15],
 '구로구': [0.53, 0.49, 0.5, 0.54, 0.58, 0.58, 0.65, 0.51, 0.64],
 '금천구': [0.86, 0.87, 0.87, 0.88, 0.91, 0.9, 0.92, 0.88, 0.91],
 '영등포구': [0.49, 0.48, 0.48, 0.4, 0.48, 0.53, 0.59, 0.45, 0.55],
 '동작구': [0.44, 0.43, 0.33, 0.44, 0.46, 0.47, 0.53, 0.43, 0.45],
 '관악구': [0.04, 0.03, -0.01, 0.06, 0.08, 0.06, 0.07, -0.03, 0.07],
 '서초구': [0.33, 0.36, 0.24, 0.37, 0.34, 0.24, 0.46, 0.33, 0.27],
 '강남구': [0.03, -0.03, -0.17, -0.09, -0.01, -0.05, 0.13, 0.02, 0.07],
 '송파구': [-0.1, -0.08, -0.14, -0.15, -0.07, 0.01, -0.2, -0.19, -0.15],
 '강동구': [0.35, 0.35, 0.09, 0.23, 0.14, 0.45, 0.47, 0.32, 0.37]}