In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings 

warnings.filterwarnings('ignore')

# 한글 폰트 문제 해결 
# matplotlib은 한글 폰트를 지원하지 않음
# os정보
import platform

# font_manager : 폰트 관리 모듈
# rc : 폰트 변경 모듈
from matplotlib import font_manager, rc
# unicode 설정
plt.rcParams['axes.unicode_minus'] = False

if platform.system() == 'Darwin':
    rc('font', family='AppleGothic') # os가 macos
elif platform.system() == 'Windows':
    path = 'c:/Windows/Fonts/malgun.ttf' # os가 windows
    font_name = font_manager.FontProperties(fname=path).get_name()
    rc('font', family=font_name)
else:
    print("Unknown System")

In [3]:
pay = pd.read_csv("../../Data/companies/정제_월평균임금_임금상승률(2013~2022).csv")
industries = pd.read_csv("../../Data/companies/정제_업종_전부(2013~2020).csv")
companies = pd.read_csv("../../Data/companies/정제_시도별_전체_기업수(2013~2020).csv")

In [4]:
pay.set_index('년도', drop=True, inplace=True)
industries.set_index('년도', drop=True, inplace=True)
companies.set_index('년도', drop=True, inplace=True)

In [5]:
print('pay row 수:', len(pay))
print('industries row 수:', len(industries))
print('companies row 수:', len(companies))

pay row 수: 170
industries row 수: 136
companies row 수: 136

In [6]:
# industries.set_index('년도', drop=True, inplace=True)
# industries.to_csv("../../Data/companies/정제_업종_전부(2013~2020).csv", encoding='utf-8', index=False)

In [7]:
industries

,"협회 및 단체, 수리 및 기타 개인서비스업_활동","협회 및 단체, 수리 및 기타 개인서비스업_신생","협회 및 단체, 수리 및 기타 개인서비스업_소멸","예술, 스포츠 및 여가관련 서비스업_활동","예술, 스포츠 및 여가관련 서비스업_신생","예술, 스포츠 및 여가관련 서비스업_소멸",보건업 및 사회복지 서비스업_활동,보건업 및 사회복지 서비스업_신생,보건업 및 사회복지 서비스업_소멸,교육서비스업_활동,...,"전기, 가스, 증기 및 공기조절 공급업_활동","전기, 가스, 증기 및 공기조절 공급업_신생","전기, 가스, 증기 및 공기조절 공급업_소멸",제조업_활동,제조업_신생,제조업_소멸,광업_활동,광업_신생,광업_소멸,시도
년도,,,,,,,,,,,,,,,,,,,,,
2013,47929,5870,6229,24426,4488,4716,18641,1666,1389,28184,...,163,45,9,74080,7362,6401,53,6,4,서울특별시
2013,17554,1892,2093,6967,1146,1292,5023,394,280,8354,...,39,14,1,35083,3208,2694,13,1,1,부산광역시
2013,11126,1400,1301,5129,862,929,3773,245,192,6666,...,86,11,1,29884,2640,1936,12,4,4,대구광역시
2013,12099,1931,1769,6050,1218,1283,3263,298,223,5995,...,54,10,2,30778,3168,2594,21,1,1,인천광역시
2013,7586,1086,1086,3430,782,841,2186,221,166,4819,...,151,62,5,9376,1051,808,15,2,0,광주광역시
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020,11770,1675,1260,3933,713,674,2696,132,94,6035,...,18102,5800,496,14377,1573,1216,90,9,8,전라북도
2020,11167,1733,1342,3663,752,670,2198,101,83,4567,...,10767,3502,378,14892,1720,1310,528,128,117,전라남도
2020,17024,2354,1827,5765,930,983,3021,119,120,7648,...,7750,2617,260,34547,3277,2702,189,13,20,경상북도
2020,21223,3176,2337,6929,1155,1185,4074,197,159,11810,...,4140,1286,130,47130,4090,3648,86,11,9,경상남도
2020,4745,703,595,2107,400,276,1000,43,22,2682,...,995,290,22,3302,383,263,18,0,2,제주특별자치도

In [8]:
aa = pd.merge(companies, pay, on=['년도', '시도'], how='inner')
aa

           시도       활동      신생      소멸  상용_월평균_임금  임금상승률
년도
2013    서울특별시  1258829  168425  150812  3168798.0    5.4
2013    부산광역시   370922   49110   43743  2520222.0    2.7
2013    대구광역시   255803   33186   28898  2315945.0    2.3
2013    인천광역시   278236   41563   37133  2609457.0    4.0
2013    광주광역시   142802   22274   19665  2417477.0    4.2
...       ...      ...     ...     ...        ...    ...
2020     전라북도   224779   35752   23203  3028036.0    1.2
2020     전라남도   219445   34249   22803  3252923.0    0.5
2020     경상북도   322277   44946   33437  3318498.0    1.7
2020     경상남도   403797   58729   45268  3260329.0    2.2
2020  제주특별자치도   102151   16875   12269  2726806.0    0.6

[136 rows x 6 columns]

In [9]:
industries.columns

Index(['협회 및 단체, 수리 및 기타 개인서비스업_활동', '협회 및 단체, 수리 및 기타 개인서비스업_신생',
       '협회 및 단체, 수리 및 기타 개인서비스업_소멸', '예술, 스포츠 및 여가관련 서비스업_활동',
       '예술, 스포츠 및 여가관련 서비스업_신생', '예술, 스포츠 및 여가관련 서비스업_소멸',
       '보건업 및 사회복지 서비스업_활동', '보건업 및 사회복지 서비스업_신생', '보건업 및 사회복지 서비스업_소멸',
       '교육서비스업_활동', '교육서비스업_신생', '교육서비스업_소멸', '사업 시설관리, 사업지원 및 임대 서비스업_활동',
       '사업 시설관리, 사업지원 및 임대 서비스업_신생', '사업 시설관리, 사업지원 및 임대 서비스업_소멸',
       '전문, 과학 및 기술서비스업_활동', '전문, 과학 및 기술서비스업_신생', '전문, 과학 및 기술서비스업_소멸',
       '부동산업_활동', '부동산업_신생', '부동산업_소멸', '금융 및 보험업_활동', '금융 및 보험업_신생',
       '금융 및 보험업_소멸', '정보통신업_활동', '정보통신업_신생', '정보통신업_소멸', '숙박 및 음식점업_활동',
       '숙박 및 음식점업_신생', '숙박 및 음식점업_소멸', '운수 및 창고업_활동', '운수 및 창고업_신생',
       '운수 및 창고업_소멸', '도매 및 소매업_활동', '도매 및 소매업_신생', '도매 및 소매업_소멸', '건설업_활동',
       '건설업_신생', '건설업_소멸', '수도, 하수 및 폐기물처리, 원료재생업_활동',
       '수도, 하수 및 폐기물처리, 원료재생업_신생', '수도, 하수 및 폐기물처리, 원료재생업_소멸',
       '전기, 가스, 증기 및 공기조절 공급업_활동', '전기, 가스, 증기 및 공기조절 공급업_신생',
       '전기, 가스, 증기 및 공기조절 공급업_소멸', '제조업_활동', '제조업_신생', '제조업_소멸', '광업_활동',
       '광업_신생', '광업_소멸', '시도'],
      dtype='object')

In [13]:
dd = pd.merge(aa, industries, on=['년도', '시도'], how='inner')
dd

,시도,활동,신생,소멸,상용_월평균_임금,임금상승률,"협회 및 단체, 수리 및 기타 개인서비스업_활동","협회 및 단체, 수리 및 기타 개인서비스업_신생","협회 및 단체, 수리 및 기타 개인서비스업_소멸","예술, 스포츠 및 여가관련 서비스업_활동",...,"수도, 하수 및 폐기물처리, 원료재생업_소멸","전기, 가스, 증기 및 공기조절 공급업_활동","전기, 가스, 증기 및 공기조절 공급업_신생","전기, 가스, 증기 및 공기조절 공급업_소멸",제조업_활동,제조업_신생,제조업_소멸,광업_활동,광업_신생,광업_소멸
년도,,,,,,,,,,,,,,,,,,,,,
2013,서울특별시,1258829,168425,150812,3168798.0,5.4,47929,5870,6229,24426,...,27,163,45,9,74080,7362,6401,53,6,4
2013,부산광역시,370922,49110,43743,2520222.0,2.7,17554,1892,2093,6967,...,30,39,14,1,35083,3208,2694,13,1,1
2013,대구광역시,255803,33186,28898,2315945.0,2.3,11126,1400,1301,5129,...,24,86,11,1,29884,2640,1936,12,4,4
2013,인천광역시,278236,41563,37133,2609457.0,4.0,12099,1931,1769,6050,...,35,54,10,2,30778,3168,2594,21,1,1
2013,광주광역시,142802,22274,19665,2417477.0,4.2,7586,1086,1086,3430,...,7,151,62,5,9376,1051,808,15,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020,전라북도,224779,35752,23203,3028036.0,1.2,11770,1675,1260,3933,...,25,18102,5800,496,14377,1573,1216,90,9,8
2020,전라남도,219445,34249,22803,3252923.0,0.5,11167,1733,1342,3663,...,31,10767,3502,378,14892,1720,1310,528,128,117
2020,경상북도,322277,44946,33437,3318498.0,1.7,17024,2354,1827,5765,...,51,7750,2617,260,34547,3277,2702,189,13,20
2020,경상남도,403797,58729,45268,3260329.0,2.2,21223,3176,2337,6929,...,45,4140,1286,130,47130,4090,3648,86,11,9
2020,제주특별자치도,102151,16875,12269,2726806.0,0.6,4745,703,595,2107,...,5,995,290,22,3302,383,263,18,0,2

In [14]:
dd.to_csv("../../Data/companies/정제_임금_기업_통합(2013~2020).csv", encoding='utf-8')

In [12]:
dd

,시도,활동,신생,소멸,상용_월평균_임금,임금상승률,"협회 및 단체, 수리 및 기타 개인서비스업_활동","협회 및 단체, 수리 및 기타 개인서비스업_신생","협회 및 단체, 수리 및 기타 개인서비스업_소멸","예술, 스포츠 및 여가관련 서비스업_활동",...,"수도, 하수 및 폐기물처리, 원료재생업_소멸","전기, 가스, 증기 및 공기조절 공급업_활동","전기, 가스, 증기 및 공기조절 공급업_신생","전기, 가스, 증기 및 공기조절 공급업_소멸",제조업_활동,제조업_신생,제조업_소멸,광업_활동,광업_신생,광업_소멸
년도,,,,,,,,,,,,,,,,,,,,,
2013,서울특별시,1258829,168425,150812,3168798.0,5.4,47929,5870,6229,24426,...,27,163,45,9,74080,7362,6401,53,6,4
2013,부산광역시,370922,49110,43743,2520222.0,2.7,17554,1892,2093,6967,...,30,39,14,1,35083,3208,2694,13,1,1
2013,대구광역시,255803,33186,28898,2315945.0,2.3,11126,1400,1301,5129,...,24,86,11,1,29884,2640,1936,12,4,4
2013,인천광역시,278236,41563,37133,2609457.0,4.0,12099,1931,1769,6050,...,35,54,10,2,30778,3168,2594,21,1,1
2013,광주광역시,142802,22274,19665,2417477.0,4.2,7586,1086,1086,3430,...,7,151,62,5,9376,1051,808,15,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020,전라북도,224779,35752,23203,3028036.0,1.2,11770,1675,1260,3933,...,25,18102,5800,496,14377,1573,1216,90,9,8
2020,전라남도,219445,34249,22803,3252923.0,0.5,11167,1733,1342,3663,...,31,10767,3502,378,14892,1720,1310,528,128,117
2020,경상북도,322277,44946,33437,3318498.0,1.7,17024,2354,1827,5765,...,51,7750,2617,260,34547,3277,2702,189,13,20
2020,경상남도,403797,58729,45268,3260329.0,2.2,21223,3176,2337,6929,...,45,4140,1286,130,47130,4090,3648,86,11,9
2020,제주특별자치도,102151,16875,12269,2726806.0,0.6,4745,703,595,2107,...,5,995,290,22,3302,383,263,18,0,2